services:
  - docker
  - postgresql

before_script:
  - docker-compose up --build -d
  - sleep 15
  - docker-compose run web sh migrate.sh

script:
  - docker-compose-test.sh

after_script:
  - docker-compose down

notifications:
  email:
    - pete.topleft@gmail.com
