services:
  - docker
  - postgresql

before_script:
  - docker-compose up --build -d

script:
  - docker-compose run web sh migrate.sh
  - docker-compose run web npm run test

after_script:
  - docker-compose down

notifications:
  email:
    - pete.topleft@gmail.com
