
language: node_js

node_js:
- '9'

services:
- docker
- postgresql

before_install:
- psql -c 'create database basic_db_test;' -U postgres
- npm install knex -g
- sleep 10

before_script:
-  docker-compose run web sh migrate.sh

script:
- docker-compose run web npm run test

after_script:
  - docker-compose down

notifications:
  email:
    - pete.topleft@gmail.com
