services:
  - docker
  - postgresql

before_script:
  - docker-compose up --build -d

script:
  - sh docker-compose-test.sh

after_script:
  - docker-compose down

after_success:
  - git config --local user.name "topleft"
  - git config --local user.email "pete.topleft@gmail.com"
  - export VERSION=$(npm version patch)
  - git tag $VERSION
  - git push
  - git push --tags

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true

notifications:
  email:
    - pete.topleft@gmail.com
