language: node_js

node_js:
- '9'

services:
- docker
- postgresql

before_install:
- psql -c 'create database basic_db_test;' -U postgres
- docker build -f Dockerfile.test -t topleft/api-boiler-test .

before_script:
- npm install knex -g
- knex migrate:latest --env test

script:
- sh test.sh

notifications:
  email:
    - pete.topleft@gmail.com
