services:
  - docker
  - postgresql

before_script:
  - docker-compose up --build -d

script:
  - docker-compose-test.sh

after_script:
  - docker-compose down

notifications:
  email:
    - pete.topleft@gmail.com
