language: node_js

node_js:
- '9'

services:
- docker
- postgresql

before_install:
- psql -c 'create database basic_db_test;' -U postgres
- npm install knex
- BASIC_DB_TEST=postgres://postgres@localhost:5432/basic_db_test knex -- migrate:latest --env test

script:
- sh test.sh

notifications:
  email:
    - pete.topleft@gmail.com
