FROM node:10

WORKDIR /usr/src

COPY knexfile.js ./
COPY package*.json ./
COPY .eslintrc ./
COPY docker-test-entrypoint.sh ./

RUN npm install

COPY ./src ./src/.
COPY ./test ./test/.

ENTRYPOINT ["sh", "./docker-test-entrypoint.sh"]

